language: cpp
os: 
  - linux
  - osx

dist: 
  - bionic

osx_image: 
  - xcode11.3
  - xcode10.2

compiler: 
  - gcc
  - clang

addons:
  apt:
    packages: git libeigen3-dev cmake libboost-log-dev libboost-thread-dev libboost-system-dev libboost-program-options-dev libasound2-dev libprotobuf-dev protobuf-compiler libimlib2-dev
  homebrew:
    packages:
      - eigen
      - cmake
      - protobuf
      - boost
      - imlib2

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
