language: cpp
os: 
  - linux
  - osx

dist: bionic
compiler: 
  - gcc
  - clang

addons:
  apt:
    packages: git libeigen3-dev cmake libboost-log-dev libboost-thread-dev libboost-system-dev libboost-program-options-dev libasound2-dev libprotobuf-dev protobuf-compiler libimlib2-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install eigen cmake protobuf boost imlib2; fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
