server {
    listen 5173 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location /CubeSimulator/ {
        alias /app/dist/CubeSimulator/;
        index index.html;
        try_files $uri $uri/ /CubeSimulator/index.html;
    }

    location /matrix-ws {
        proxy_pass http://localhost:1337;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # Redirect root to /CubeSimulator/
    location = / {
        return 301 /CubeSimulator/;
    }
}
